version: '3'

services:
  queue-vis:
    image: queue-vis
    build: .
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      ["5672:15672"]